### ISSUE TITLE
It's been used to extract from a database (not sql file) to  another one?

### ISSUE THREAD

**Issue by manel00** [Kazanz/easy-etl#1]
Hi,

First of all, seems interesting your software for my purpose, is it for connect to a database for example and do some extraction to transform/load to another one? can make union from 2 databases to load into final database?

Thank you very much

**Comment by manel00** [comment]
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "gesco_pkey"
DETAIL:  Key (id)=(1) already exists.

my table has id autoincremental, how to avoid this problem? Thanks

**Comment by exit99** [comment]
@manel00 Yes, you can use it to connect one database to another and load data into the new one after performing some transformations on the source data.

The example in the quickstart is a good place to start.  I'll explain it in more detail here though,

# Quick start explained in detail

```python
import dataset
from easy_etl import ETLProcess

src_db = dataset.connect("sqlite:///src.db")
target_db = dataset.connect("sqlite:///target.db")

process = ETLProcess(src_db, target_db, "target_tablename")
process.extract("query.sql")  
process.transform("name").default("Unknown")  
process.transform("state", "country").upper()  
process.load()
```

`src_db` is the database you will be retrieving data from
`target_db` is the database you will be sending the data to

in this case you would have a `query.sql` file that looks like this:
```
select name, state, country from SOME_TABLE_IN_SRC_DB;
```
Lets imagine the data returned by that query looks like this:

<table>
<thead>
<tr><th>Name</th><th>State</th><th>Countr</th></tr>
</thead>
<tbody>
    <tr>
        <td>John</td>
        <td>fl</td>
        <td>Usa</td>
    </tr>
    <tr>
        <td>Carl</td>
        <td>NY</td>
        <td>usa</td>
    </tr>
    <tr>
        <td>NULL</td>
        <td>ca</td>
        <td>usa</td>
    </tr>
</tbody>
</table>

where NULL is actually a NULL value in the database.

During the transform process the line
`process.transform("name").default("Unknown")  `

Will replace all NULL values in the `name` column with the string value `"Unknown"`.

The line `process.transform("state", "country").upper()  `

Will run the python `upper` function on all values in both columns `state` and `country` before loading them into the new database.

`process.load()` will create a new table in the target database named `target_tablename` and the values in the table will look like the following:

<table>
<thead>
<tr><th>Name</th><th>State</th><th>Countr</th></tr>
</thead>
<tbody>
    <tr>
        <td>John</td>
        <td>FL</td>
        <td>USA</td>
    </tr>
    <tr>
        <td>Carl</td>
        <td>NY</td>
        <td>USA</td>
    </tr>
    <tr>
        <td>Unknown</td>
        <td>CA</td>
        <td>USA</td>
    </tr>
</tbody>
</table>

# Doing unions

You can do anything in sql that you want ahead of time so unions between tables in a single database is as simple as writing a `JOIN` query.

There is no builtin support to make unions between 2 databases.  The way I would do it is have an intermediate process.  

```python
src1_db = dataset.connect("sqlite:///src1.db")
src2_db = dataset.connect("sqlite:///src2.db")
intermediate_db = dataset.connect("sqlite:///intermediate.db")
target_db = dataset.connect("sqlite:///target.db")

# Extract from src1_db into intermediate_db
process = ETLProcess(src1_db, intermediate_db, 'src1_t)
process.extract("SELECT id, value FROM table1")  
process.load()

# Extract from src2_db into intermediate_db
process = ETLProcess(src2_db, intermediate_db, 'src2_t)
process.extract("SELECT id, src1_id, value FROM table1")  
process.load()

# Extract from intermediate_db into final database
# This is where you would do your Union
process = ETLProcess(intermediate_db, target_db, 'final_table')
process.extract("SELECT * FROM src2_t INNER JOIN src1_t ON src1_t.id == src2_t.src1_id;")  
process.load()
```

We can probably make some sort of internal API to do these types of joins easier.  I am open to ideas.

**Comment by manel00** [comment]
I'm sorry but have too many problems because easy-etl just insert into the second DB just the first row.
 How should I deal with autoincremental id (first column)? 

`TypeError: unsupported operand type(s) for +=: 'odict_keys' and 'list'`

It doesn't work with 3.6+ Python. 

On 2.7 works perfectly (at least from 1 db to 2 db)

**Comment by manel00** [comment]
Please to insert a timestamp on the 2 db, could you give me some best practice to insert new columns (+data) on second db? Thank you so much for your time

```
process = ETLProcess(src_db, target_db, "TABLE")
process.extract("SELECT * FROM TABLE")

table = target_db['TABLE']

table.insert(dict(timestamp=myTS))

process.transform("age","salary").default("None")  

process.transform("nombre").upper()

process.load(upsert_fields=["timestamp"],ensure=True)
```

**Comment by exit99** [comment]
Thanks for brining up the version incompatibility, will make a port to 3.6+

If I understand your question, I think you are wanting to add some [middleware](https://github.com/kazanz/easy-etl#formatting-extracted-data-with-middleware)?

```python
def add_timestamp(results):
    timestamp = datetime.now()
    new_results = []
    for row in results:
        row['timestamp'] = timestamp
        new_results.append(row)
    return new_results

process = ETLProcess(src_db, target_db, "TABLE")
process.extract("SELECT * FROM TABLE")
process.middleware(add_timestamp)   # This line will add the timestamp in the transform step
process.transform("age","salary").default("None")  
process.transform("nombre").upper()
process.load(upsert_fields=["timestamp"],ensure=True)

**Comment by manel00** [comment]
Hi! I know I'm asking for too much, but would be so kind if you could tell me the way to become the new column (timestamp) the latest. Thank you very much

**Comment by exit99** [comment]
Can you clarify what you mean by "the latest"?

**Comment by manel00** [comment]
yes, it means the column at the rightest place of the table, actually it appears on the second place on the table (so ugly). Thanks



Enviado desde mi Redmi Note 4
El Zachary Kazanski <notifications@github.com>, 23 abr. 2018 7:10 p. m. escribió:

Can you clarify what you mean by "the latest"?

**Comment by exit99** [comment]
https://stackoverflow.com/questions/20574113/sqlite3-how-to-reorder-columns-in-a-table#20574263

Thats outside of scope for this project.  If you need columns rearranged in a table, take a look at that stackoverflow.
