### ISSUE TITLE
Duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by exit99** [Kazanz/easy-etl#2]
@manel00

> sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "gesco_pkey"
> DETAIL: Key (id)=(1) already exists.
> 
> my table has id autoincremental, how to avoid this problem? Thanks

Can you post the full traceback, and the code you are running?

**Comment by manel00** [comment]
Finally was the version of python 3.6 gives error

**Comment by manel00** [comment]
Close this one please, just Python3.6+ uncompatibility ;)

**Comment by exit99** [comment]
@manel00 If you want to run `2to3` on the codebase I will merge it in to the repo.
