### ISSUE TITLE
Invalid input syntax for type tinterval

### ISSUE THREAD

**Issue by manel00** [Kazanz/easy-etl#3]
`sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input syntax for type tinterval: " "
LINE 1: select ag.number, pu.name **| |' ' | |**pu.surname...`

Hey!  I'm trying to send a big query but gives error on this point, do you know how to deal with it?

Thank you very much

I know that's not you business, but you would be so kind ;)

**Comment by exit99** [comment]
I cannot see you whole query, so I'm not sure where the error is, but you can checkout this stackoverflow:

https://stackoverflow.com/questions/28283807/invalid-input-syntax-for-type-interval#28283893

**Comment by manel00** [comment]
I'm sorry, finally got resolved changing the pipes and spaces, for concat function ;)


Thanks anyway! (Symbols seems to provoke errors)


________________________________
De: Zachary Kazanski <notifications@github.com>
Enviado: martes, 24 de abril de 2018 14:40
Para: Kazanz/easy-etl
Cc: Manel M; Author
Asunto: Re: [Kazanz/easy-etl] Invalid input syntax for type tinterval (#3)


I cannot see you whole query, so I'm not sure where the error is, but you can checkout this stackoverflow:

https://stackoverflow.com/questions/28283807/invalid-input-syntax-for-type-interval#28283893

[https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded]<https://stackoverflow.com/questions/28283807/invalid-input-syntax-for-type-interval#28283893>

postgresql - Invalid input syntax for type interval ...<https://stackoverflow.com/questions/28283807/invalid-input-syntax-for-type-interval#28283893>
stackoverflow.com
I am encountering an issue where I am not able to add intervals to a date in postgresql. In MySql I would do this: date_add('2015-02-02', interval -46 day) with the corresponding statement in
